name: documents_picker
description: A new Flutter plugin to get documents.
version: 0.0.1
author: Lucas Britto <l_demello@hotmail.com>
homepage: https://github.com/lubritto/Flutter_Documents_Picker

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.documentspicker
    pluginClass: DocumentsPickerPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
